name: open-ecommerce
networks:
    open_ecommerce_network:
        driver: bridge
services:
    auth_db:
        container_name: open-ecommerce-auth-db
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root@123
            - MYSQL_DATABASE=auth_db
            - MYSQL_USER=auth
            - MYSQL_PASSWORD=Auth@123
        ports:
            - '3307:3306'
        healthcheck:
            test: mysqladmin ping -u root --password=$$MYSQL_ROOT_PASSWORD
            timeout: 20s
            retries: 10
        volumes:
            - open_ecommerce_auth_db_dist:/var/lib/mysql
            - ./.docker/my.cnf:/etc/mysql/my.cnf
        networks:
            - open_ecommerce_network
    redis:
        container_name: open-ecommerce-redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - open_ecommerce_redis_dist:/data
        command: redis-server --save 20 1 --loglevel warning --requirepass 123456
        networks:
            - open_ecommerce_network
    # zookeeper:
    #     container_name: open-ecommerce-zookeeper
    #     image: docker.io/bitnami/zookeeper:3.9
    #     ports:
    #         - '2181:2181'
    #     environment:
    #         - ALLOW_ANONYMOUS_LOGIN=yes
    #     volumes:
    #         - open_ecommerce_zookeeper_dist:/bitnami
    #     networks:
    #         - open_ecommerce_network
    kafka:
        container_name: open-ecommerce-broker
        image: bitnami/kafka
        restart: unless-stopped
        ports:
            - '9094:9094'
        environment:
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_KRAFT_MODE=true
        volumes:
            - open_ecommerce_kafka_dist:/bitnami
        networks:
            - open_ecommerce_network
    kafka_ui:
        container_name: open-ecommerce-broker-ui
        restart: unless-stopped
        image: provectuslabs/kafka-ui:latest
        ports:
            - '9080:8080'
        environment:
            DYNAMIC_CONFIG_ENABLED: true
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        depends_on:
            kafka:
                condition: service_started
        networks:
            - open_ecommerce_network
volumes:
    open_ecommerce_auth_db_dist:
        driver: local
    # open_ecommerce_zookeeper_dist:
    #     driver: local
    open_ecommerce_kafka_dist:
        driver: local
    open_ecommerce_redis_dist:
        driver: local
